name: Get Test Code Coverage

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:

  runs-on: ubuntu-latest

  steps:
    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secretes.CODECOV_TOKEN }}