name: Get Test Code Coverage

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Run and Get Code Coverage
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest --cov