name: Get Test Code Coverage

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Pull Code
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install Poetry
        run: |
          python3 -m pip install --upgrade pip
          pip install poetry

      - name: Install Dependencies
        run: |
          poetry install --no-root

      - name: Test And Show Coverage Directly
        run: | 
          poetry run pytest
          poetry run pytest --cov=app test

      - name: Generate Report
        run: |
          poetry run coverage run --source=app -m pytest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
