name: Get Test Code Coverage

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setu up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get Python Version
        run: python3 -V